---
<<<<<<< HEAD
- name: nginx version
=======
- name: NGINX version
  enable_apache_lb: false
  load_balancer_is_required: false
>>>>>>> f1ce16c6a2c4aace1368f25bd8f2286a7d6ae7f3
  apt_repository:
    repo: "ppa:nginx/{{ nginx_load_balancer_version }}"
    state: "present"
  become: true
  

- name: debian | Installing NGINX
  apt:
    name: "nginx"
    state: "present"
  become: true

- name: debian | Installing Apache2 Modules
  apt:
    name: "{{ item }}"
    state: "present"
  become: true
  with_items:
    - 'libapache2-mod-rpaf'
 
